[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      connect-src 'self'
        https://*.supabase.co
        wss://*.supabase.co
        https://ykseqqeabceslsgzzuta.supabase.co
        wss://ykseqqeabceslsgzzuta.supabase.co
        https://api.stripe.com
        https://api.dicebear.com
        data: blob:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src * data: blob:;
    '''

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
